# Generated by Django 4.2.23 on 2025-08-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BriefQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вопроса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Вопрос бриф',
                'verbose_name_plural': 'Вопросы бриф',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('user_tg_name', models.CharField(blank=True, default='none', max_length=35, null=True, verbose_name='Имя пользователя в Telegram')),
                ('user_name', models.CharField(max_length=35, verbose_name='Имя пользователя')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ФИО')),
                ('grade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Класс/Курс')),
                ('school', models.CharField(blank=True, max_length=150, null=True, verbose_name='Школа/Учебное заведение')),
                ('brief_completed', models.BooleanField(default=False, verbose_name='Бриф заполнен')),
                ('current_brief_question', models.PositiveIntegerField(blank=True, null=True, verbose_name='Текущий вопрос бриф')),
                ('is_paid_current_month', models.BooleanField(default=False, verbose_name='Оплачен в текущем месяце')),
                ('last_payment_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней оплаты')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('succeeded', 'Подтвержден'), ('failed', 'Отклонен'), ('manual', 'Ручной зачет')], default='pending', max_length=20, verbose_name='Статус')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('yookassa_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа ЮKassa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('admin_comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий администратора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBriefAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Ответ пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='bot.briefquestion', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brief_answers', to='bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ на бриф',
                'verbose_name_plural': 'Ответы на бриф',
                'ordering': ['user', 'question__order'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
