# Generated by Django 5.1.6 on 2025-06-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название евента для пользователя')),
                ('chanel_name', models.CharField(max_length=50, verbose_name='Название кнала с собачкой')),
                ('price', models.IntegerField(default=1, verbose_name='Выплата юзеру за подписку')),
                ('remaining_number_of_clicks', models.IntegerField(default=1, verbose_name='Максимально возможное количество переходов по ссылке')),
                ('users', models.JSONField(blank=True, default=list, verbose_name='Пользователи перешедшие по ссылке')),
            ],
            options={
                'verbose_name': 'Евент',
                'verbose_name_plural': 'Евенты',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название товара')),
                ('goods_price', models.IntegerField(default=1, verbose_name='Цена товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('telegram_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_tg_name', models.CharField(blank=True, default='none', max_length=35, null=True, verbose_name='Имя аккаунта в телеграмм')),
                ('user_name', models.CharField(max_length=35, verbose_name='Имя')),
                ('ref_code', models.CharField(blank=True, max_length=35)),
                ('invited_referals', models.IntegerField(default=0)),
                ('last_farm', models.DateTimeField(blank=True, null=True)),
                ('coins', models.IntegerField(default=0)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
