# Generated by Django 5.1.6 on 2025-06-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='id',
            field=models.BigAutoField(auto_created=True, default=21, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_name',
            field=models.CharField(max_length=50, verbose_name='Название товара'),
        ),
    ]
