# Generated by Django 4.2.23 on 2025-08-11 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBriefComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_data', models.JSONField(help_text='Содержит все вопросы и ответы пользователя', verbose_name='Данные брифа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_briefs', to='bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Полный бриф пользователя',
                'verbose_name_plural': 'Полные брифы пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
