# Generated by Django 5.1.6 on 2025-10-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complexhomework',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AlterModelOptions(
            name='complextask',
            options={'verbose_name': 'Набор заданий', 'verbose_name_plural': 'Наборы заданий'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Ответ на домашнее задание', 'verbose_name_plural': 'Ответы на домашние задания'},
        ),
        migrations.RemoveField(
            model_name='complextask',
            name='group',
        ),
        migrations.RemoveField(
            model_name='complextask',
            name='lesson',
        ),
        migrations.AddField(
            model_name='complexhomework',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='bot.group', verbose_name='Группа'),
        ),
    ]
