# Generated by Django 5.1.6 on 2025-08-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_goods_id_alter_goods_goods_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.RemoveField(
            model_name='user',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invited_referals',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_farm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ref_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_tg_name',
        ),
        migrations.AddField(
            model_name='user',
            name='course_or_class',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Курс или класс'),
        ),
        migrations.AddField(
            model_name='user',
            name='education_type',
            field=models.CharField(blank=True, choices=[('school', 'Школа'), ('university', 'ВУЗ')], max_length=20, null=True, verbose_name='Тип образования'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='Завершена регистрация'),
        ),
    ]
