# Generated by Django 4.2.23 on 2025-08-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_userbriefcomplete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBriefAnswer',
        ),
    ]
