# Generated by Django 5.1.6 on 2025-10-18 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_complexhomework_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexhomework',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='bot.studentprofile', verbose_name='Ученик'),
        ),
    ]
