# Generated by Django 5.1.6 on 2025-08-19 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_delete_events_delete_goods_remove_user_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yookassa_payment_id', models.CharField(max_length=100, unique=True, verbose_name='ID платежа в ЮKassa')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('waiting_for_capture', 'Ожидает подтверждения'), ('succeeded', 'Успешно'), ('canceled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус платежа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание платежа')),
                ('payment_method', models.JSONField(blank=True, null=True, verbose_name='Метод оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('payment_month', models.IntegerField(verbose_name='Месяц оплаты')),
                ('payment_year', models.IntegerField(verbose_name='Год оплаты')),
                ('pricing_plan', models.CharField(max_length=50, verbose_name='Тарифный план')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплаченная сумма')),
                ('pricing_plan', models.CharField(max_length=50, verbose_name='Тарифный план')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='bot.payment', verbose_name='Платеж')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='bot.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История оплат',
                'verbose_name_plural': 'История оплат',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
