# Generated by Django 4.2.23 on 2025-08-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_delete_userbriefanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_month', '-created_at'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AddField(
            model_name='payment',
            name='academic_year',
            field=models.CharField(default='2024-2025', help_text='Например: 2024-2025', max_length=9, verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_month',
            field=models.DateField(default='2024-08-01', help_text='Первый день месяца, за который производится оплата', verbose_name='Месяц оплаты'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('user', 'payment_month', 'academic_year')},
        ),
    ]
